name: SonarQube Integration Pipeline

on:
  push:
    branches:
      - main  # Adjust to your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      sonar:
        image: sonarqube:latest
        ports:
          - 9000:9000  # Expose SonarQube port on 9000
        options: --health-cmd="curl -f http://localhost:9000/api/system/health" \
                 --health-interval=10s --health-timeout=30s --health-retries=5
        # Ensures SonarQube is ready before proceeding

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform (if not already set up in your pipeline)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9  # Use preferred version

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Apply Terraform configuration to create the SonarQube project
      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve

      # Step 5: Wait for SonarQube to be ready
      - name: Wait for SonarQube to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:9000/api/system/health; then
              echo "SonarQube is ready!"
              break
            fi
            echo "Waiting for SonarQube..."
            sleep 10
          done

      # Step 6: Run SonarQube Scan (using username and password for authentication)
      - name: Run SonarQube Scan
        run: |
          curl -u admin:admin -X POST "http://localhost:9000/api/sonarqube/scan"  # Replace with your actual scan URL
          # Replace "admin:admin" with your actual username and password in SonarQube

      # Step 7: Optional: Check SonarQube Project Status
      - name: Check SonarQube Project Status
        run: |
          curl -u admin:admin "http://localhost:9000/api/qualitygates/project_status?projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }}"
          # Replace with your actual username/password and project key
